### ISSUE TITLE
Add an endpoint to download the routing packet and metadata

### ISSUE THREAD

**Issue by ltbam** [gis-ops/routing-graph-packager#2]
It would be very helpful to have an endpoint to get the job resulting data.

I suggest an endoint like:
/jobs/6**/data**
for the zip routing packet

and something very similar for the metadata to this packet: 
/jobs/6**/meta**
metadata.json

I've seen this to server static files with Flask 
-----------------------------------------
from flask import send_from_directory
return send_from_directory(outdir, path)

**Comment by nilsnolde** [comment]
yeah sounds good, thanks!

**Comment by ltbam** [comment]
Finally we can write the output files in a smd share. we don't use http download interface anymore.
